spring.application.name=rest-service-demo

spring.h2.console.enabled=true
# Define the JDBC URL. "testdb" can be any name you choose.
spring.datasource.url=jdbc:h2:file:~/testdb

# Specify the driver class
spring.datasource.driver-class-name=org.h2.Driver

# Set username and password (default username is 'sa', password is empty)
spring.datasource.username=sa
spring.datasource.password=password

spring.sql.init.mode=always
